name: Build SiuuuTPA

on:
  push:
    branches:
      - main
      - master

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java 21 installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Maven Build
        run: mvn clean package

      - name: JAR hochladen
        uses: actions/upload-artifact@v4
        with:
          name: SiuuuTPA
          path: target/*.jar
